## Task 1
1.1 Создать новый признак Cpu_Company, который будет 
содержать только название фирмы, которая произвела CPUolution

In [2]:
import pandas as pd
df = pd.read_csv('laptop_price.csv', encoding='latin-1')

In [3]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [4]:
df['Cpu_Company'] =df['Cpu'].apply(lambda x: str(x).split(' ')[0])

In [5]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel

1.2 Создать новый признак Memory_Amount, который будет
содержать только количество Gb памяти без указания типа
носителя

In [8]:
def convert(x):
    res = 0
    memory = str(x).split(' ')[0]
    if memory.endswith('GB'):
        res = memory.replace('GB', '')
    elif memory.endswith('TB'):
        res = float(memory.replace('TB', '')) * 1024
    return int(res)
df['Memory_Amount'] = df['Memory'].apply(convert)

In [9]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256

1.3 Создать новый признак Memory_Type, который будет
содержать только тип носителя (HDD/SDD/др.)

In [10]:
def convert_type(x):
    return str(x).split('B')[-1]

df['Memory_Type'] = df['Memory'].apply(convert_type)
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

1.4 Удалите признаки Memory и ScreenResolution

In [11]:
df.drop(columns=['Memory', 'ScreenResolution'], inplace= True)

In [12]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

## Task 2
2.1 Создайте признак SSD, который изначально равен 0

In [21]:
df['SSD'] = 0
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,0
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,0

2.2 Поставьте в признаке SSD 1, если ноутбук
действительно с типом носителя SSD

In [24]:
df.loc[df['Memory_Type'] == ' SSD', 'SSD'] = 1
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,1
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,1
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,1

2.3 Уберите в признаке Weight значения 'kg' и поменяйте его
тип данных на вещественный

In [28]:
df['Weight'] = df['Weight'].str.replace('kg', '')
df['Weight'] = df['Weight'].astype('float')
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD,1
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,Flash Storage,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD,1
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD,1

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   laptop_ID      1303 non-null   int64
 1   Company        1303 non-null   object
 2   Product        1303 non-null   object
 3   TypeName       1303 non-null   object
 4   Inches         1303 non-null   float64
 5   Cpu            1303 non-null   object
 6   Ram            1303 non-null   object
 7   Gpu            1303 non-null   object
 8   OpSys          1303 non-null   object
 9   Weight         1303 non-null   float64
 10  Price_euros    1303 non-null   float64
 11  Cpu_Company    1303 non-null   object
 12  Memory_Amount  1303 non-null   int64
 13  Memory_Type    1303 non-null   object
 14  SSD            1303 non-null   int64
dtypes: float64(3), int64(3), object(9)
memory usage: 152.8+ KB

## Task 3

Создайте датафрейм с клиентами:
clients = pd.DataFrame({
 'client_id': [45, 32, 67, 33, 43],
 'laptop_id': [506, 398, 710, 120, 1999]
})
laptop_id - это индексы датафрейма с ноутбуками

In [35]:
clients = pd.DataFrame({
    'client_id': [45, 32, 67, 33, 43],
    'laptop_id': [506, 398, 710, 120, 1999]
})
clients.head()

   client_id  laptop_id
0         45        506
1         32        398
2         67        710
3         33        120
4         43       1999

3.1 Присоедините к таблице clients данные по ноутбукам
через метод join

In [36]:
clients_id = clients.set_index('laptop_id')

joined = clients_id.join(df)
joined.head()

,client_id,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
laptop_id,,,,,,,,,,,,,,,,
506,45,513.0,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,2.00,1224.0,Intel,256.0,HDD,0.0
398,32,405.0,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78,2712.0,Intel,256.0,SSD,1.0
710,67,718.0,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.50,1249.0,Intel,128.0,HDD,0.0
120,33,123.0,Acer,Spin 3,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Intel HD Graphics 620,Windows 10,2.10,479.0,Intel,1024.0,HDD,0.0
1999,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

3.2 Присоедините к таблице clients данные по ноутбукам
через метод merge

In [37]:
df['laptop_ID'] = df.index
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD,1
1,1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,Flash Storage,0
2,2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD,1
3,3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD,1
4,4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD,1

In [47]:
merged = clients.merge(df, left_on='laptop_id', right_on='laptop_ID')
merged.head()

,client_id,laptop_id,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,45,506,506,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,2.00,1224.0,Intel,256,HDD,0
1,32,398,398,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78,2712.0,Intel,256,SSD,1
2,67,710,710,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.50,1249.0,Intel,128,HDD,0
3,33,120,120,Acer,Spin 3,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Intel HD Graphics 620,Windows 10,2.10,479.0,Intel,1024,HDD,0

## Task 4
4.1 Найдите среднюю стоимость ноутбуков в зависимости
от компании производителя
Отсортируйте от меньшей стоимости к большей

In [50]:
df.groupby('Company').agg({'Price_euros': 'mean'}).sort_values('Price_euros')

           Price_euros
Company
Vero        217.425000
Mediacom    295.000000
Chuwi       314.296667
Acer        626.775825
Fujitsu     729.000000
HP         1067.774854
Lenovo     1086.384444
Asus       1104.169367
Xiaomi     1133.462500
Dell       1186.068990
Toshiba    1267.812500
Samsung    1413.444444
Huawei     1424.000000
Apple      1564.198571
Microsoft  1612.308333
Google     1677.666667
MSI        1728.908148
LG         2099.000000
Razer      3346.142857

4.2 Найдите минимальную, среднюю и максимальную
стоимости ноутбуков в зависимости от производителя
процессора

In [51]:
df.groupby('Cpu_Company').agg({'Price_euros': ['min', 'mean', 'max']})

            Price_euros
                    min         mean     max
Cpu_Company
AMD               199.0   560.638871  2199.0
Intel             174.0  1152.214145  6099.0
Samsung           659.0   659.000000   659.0

4.3 Постройте таблицу с подсчетом количества ноутбуков в
данных в зависимости от производителя CPU и ОЗУ

In [53]:
df.pivot_table(index='Cpu_Company', columns='Ram', values='Weight', aggfunc='count', fill_value=0)

Ram          12GB  16GB  24GB  2GB  32GB  4GB  64GB  6GB  8GB
Cpu_Company
AMD             2     3     0    1     0   31     0   13   12
Intel          23   197     3   21    17  343     1   28  607
Samsung         0     0     0    0     0    1     0    0    0

4.4 Постройте таблицу с подсчетом средней стоимости
ноутбуков в данных в зависимости от операционной
системы и GB памяти

In [56]:
df.groupby(['OpSys', 'Memory_Amount']).agg({'Price_euros': 'mean'}).unstack('Memory_Amount').fillna(0)

              Price_euros                                               \
Memory_Amount        8       16          32          64           128
OpSys
Android               0.0    0.00    0.000000  434.000000     0.000000
Chrome OS             0.0  305.38  412.454545  774.333333  1275.000000
Linux                 0.0    0.00    0.000000    0.000000   742.250000
Mac OS X              0.0    0.00    0.000000    0.000000  1099.000000
No OS                 0.0    0.00    0.000000    0.000000   562.140000
Windows 10         2249.0    0.00  270.001471  499.716000  1026.489167
Windows 10 S          0.0    0.00    0.000000  308.995000  1039.000000
Windows 7             0.0    0.00    0.000000    0.000000  1320.323333
macOS                 0.0    0.00    0.000000    0.000000  1119.315000

                                                                             \
Memory_Amount    180     240          256         500     508          512
OpSys
Android           0.0     0.0     0.000000    0.000000     0.0     0.000000
Chrome OS         0.0     0.0  1559.000000    0.000000     0.0  2199.000000
Linux             0.0     0.0   811.638125  389.056364     0.0     0.000000
Mac OS X          0.0     0.0  1311.994000    0.000000     0.0  1222.000000
No OS             0.0     0.0   782.989286  404.675385     0.0  1098.500000
Windows 10     1073.5  3100.0  1334.456872  664.717647     0.0  1911.985285
Windows 10 S      0.0     0.0  1668.950000    0.000000     0.0  2589.000000
Windows 7      1199.0     0.0  1846.466800  924.048333  1002.0  2235.396667
macOS             0.0     0.0  1600.370000    0.000000     0.0  2180.870000


Memory_Amount         1024      2048
OpSys
Android           0.000000    0.0000
Chrome OS         0.000000    0.0000
Linux           581.401290    0.0000
Mac OS X          0.000000    0.0000
No OS           540.539600  594.0000
Windows 10      904.827906  666.9475
Windows 10 S      0.000000    0.0000
Windows 7      1539.666667    0.0000
macOS             0.000000    0.0000

## Task 5

Ответьте на несколько вопросов, используя методы группировки

5.1 Ноутбуков каких компаний и с каким процессором
больше?

In [59]:
pd.crosstab(index=df['Company'], columns='Cpu_Company').sort_values('Cpu_Company')

col_0      Cpu_Company
Company
Huawei               2
LG                   3
Chuwi                3
Google               3
Fujitsu              3
Vero                 4
Xiaomi               4
Microsoft            6
Mediacom             7
Razer                7
Samsung              9
Apple               21
Toshiba             48
MSI                 54
Acer               103
Asus               158
HP                 274
Lenovo             297
Dell               297

5.2 С каким типом памяти и с каким объемом памяти
больше ноутбуков?

In [60]:
pd.crosstab(index=df['Memory_Type'], columns=df['Memory_Amount'])

Memory_Amount,8,16,32,64,128,180,240,256,500,508,512,1024,2048
Memory_Type,,,,,,,,,,,,,
Flash Storage,0,7,38,15,4,0,0,8,0,0,2,0,0
HDD,0,0,1,1,97,0,0,85,132,0,17,227,16
Hybrid,0,0,0,0,0,0,0,1,0,1,1,9,0
SSD,1,3,6,1,76,5,1,414,0,0,120,14,0